apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simple-api
spec:
  secretName: simple-api-certificate
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: simple-api-secrets
        key: ASPNETCORE_Kestrel__Certificates__Default__Password
  duration: 17520h
  renewBefore: 4380h
  commonName: localhost