apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
  namespace: simple-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_myaks_chipsaks_northeurope
spec:
  loadBalancerIP: 20.82.227.28
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8080
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: simple-api